# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Determining the origin of wine using physiochemical properties"
author: "Hina Bandukwala, Yimeng Xia, Sean McKay, Julia Everitt"
date: "2023-12-02"
sphinx:
  config:
    bibtex_reference_style: author_year
execute:
  execute_notebooks: force 
bibtex_bibfiles:
    - references.bib

