# Install the conda environment with the following command:
# conda env create -f environment.yaml
# Once you install it, you should be able to see it in your Jupyter Lab. 
# If not, check the documentation here: https://ipython.readthedocs.io/en/stable/install/kernel_install.html
name: 'wine-origin-prediction'
channels:
    - conda-forge
    - anaconda
    - defaults
dependencies:
    - python=3.11.*
    - ipykernel
    - nb_conda_kernels
    - pandas>=2.1.1
    - matplotlib>=3.2.2
    - scikit-learn>=1.3.1    
    - requests>=2.24.0
    - ipython
    - altair=5.1.2
    - vl-convert-python  # For saving altair charts as static images
    - vegafusion  # For working with charts > 5,000 graphical objects
    - vegafusion-python-embed  # Same as the previous one
    - vegafusion-jupyter  # For working with charts > 100,000 graphical objects
    - pip>=23.2.1
    - pip:
        - ucimlrepo
        - pytest
