# Install the conda environment with the following command:
# conda env create -f environment.yaml
# Once you install it, you should be able to see it in your Jupyter Lab. 
# If not, check the documentation here: https://ipython.readthedocs.io/en/stable/install/kernel_install.html
name: 'wine-origin-prediction'
channels:
    - conda-forge
    - anaconda
    - defaults
dependencies:
    - python=3.11.*
    - ipykernel=6.26.0
    - nb_conda_kernels=2.3.1
    - pandas=2.1.1
    - matplotlib=3.8.2
    - scikit-learn=1.3.1    
    - requests=2.24.0
    - ipython=8.17.2
    - altair=5.1.2
    - vl-convert-python=1.1.0  # For saving altair charts as static images
    - vegafusion=1.4.5  # For working with charts > 5,000 graphical objects
    - vegafusion-python-embed=1.4.5  # Same as the previous one
    - vegafusion-jupyter=1.4.5  # For working with charts > 100,000 graphical objects
    - jupyter-book=0.15.1
    - pip=23.2.1
    - pip:
        - ucimlrepo==0.0.3
        - pytest==7.4.3
        - click==8.1.7
